### ISSUE TITLE
Pressure Pipe Networks v1.1.21

### ISSUE THREAD

**Issue by mzjensen** [paoloemilioserra/Civil3dToolkit#57]
The _PressurePipe.Curve_ and _PressurePipe.Curve2D_ both return null in v1.1.21. The issue does not exist in v1.1.19. Log file attached.

[Autodesk_Civil3DToolkit.log](https://github.com/paoloemilioserra/Civil3dToolkit/files/5948777/Autodesk_Civil3DToolkit.log)

**Comment by paoloemilioserra** [comment]
Thanks for reporting this, completely forgot to close the loop on this. I've found a better way to extract solid representation of pressure parts but the curve representation in 3D creates some issues with Curve pipes. Currently they are represented as arcs rather than Helixes, I'll have to look into that

**Comment by paoloemilioserra** [comment]
fixed in 1.1.22
